---
  env:
    es6: true
    node: true
    mocha: true
    mongo: true

  parser: "esprima"

  parserOptions:
    ecmaVersion: 6
    sourceType: "module"
    ecmaFeatures:
      jsx: false

  rules:
    indent: [1, 2]
    object-curly-spacing: [1, "always"]
    semi: [1, "never"]
    spaced-comment: [1, "always"]
    space-before-function-paren: [1, "always"]
    space-before-blocks: [1, "always"]

    strict: [1, "safe"]

    # Best practice
    curly: [2,  "multi-line"]
    eqeqeq: [1, "smart"]
    no-loop-func: 2
    no-alert: 2
    yoda: [2, "never"]

    #node
    global-require: 0
